micronaut:
  application:
    name: jwt_auth_example
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
netty:
  default:
    allocator:
      max-order: 3
